### ISSUE TITLE
security: lots of secret contents should be hidden

### ISSUE THREAD

**Issue by TangliziGit** [nju-softeng/dop-server#9]
# Security Vulnerability Report

**缺陷描述 / Describe the vulnerability**
Lots of secret content like database passwords, OAuth secret keys, etc. should be hidden from the public repo.
For example, the database host, username and password in `dop-server/application-server/src/main/resources/application-production.yml`:
```yaml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.29.7.157:3306/db_dop_application
    username: xxxxxxxxxxxx
    password: xxxxxxxxxxxx
```
and email secrets in `message-server/src/main/resources/application-local.yml`
```yaml
  mail:
    host: smtp.qq.com
    username: xxxxxxxxxxxxx@qq.com
    password: xxxxxxxxxxxxxx
```

**解决方案 / Describe the solution you'd like**
- use Jenkins credentials
- move secrets contents to private repo

**其他 / Additional context**
